### ISSUE TITLE
AttributeError: 'str' object has no attribute 'size'

### ISSUE THREAD

**Issue by lcqlalala** [xiaolinAndy/RODS#1]
Hello, when I run the BERTAbs interact experiment, run_CSDS.sh , I encountered a problem, as follows:
*****************
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    train_abs(args, device_id)
  File "/mnt/ssd/lcq/RODS/models/BERT_interact/train_abstractive.py", line 274, in train_abs
    train_abs_single(args, device_id)
  File "/mnt/ssd/lcq/RODS/models/BERT_interact/train_abstractive.py", line 335, in train_abs_single
    trainer.train(train_iter_fct, args.train_steps)
  File "/mnt/ssd/lcq/RODS/models/BERT_interact/models/trainer.py", line 162, in train
    report_stats)
  File "/mnt/ssd/lcq/RODS/models/BERT_interact/models/trainer.py", line 249, in _gradient_accumulation
    outputs, _, scores = self.model(src, tgts, segs, clss, mask_src, mask_tgts, mask_cls, self.args.merge, self.args.inter_weight, role_mask)
  File "/home/ubuntu/anaconda3/envs/rods/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/ssd/lcq/RODS/models/BERT_interact/models/model_builder.py", line 274, in forward
    user_outputs, agent_outputs, state_user, state_agent, user_scores, agent_scores, kl_mask_user, kl_mask_agent = self.role_decoder(tgts[0][:, :-1], tgts[1][:, :-1], top_vec, user_dec_state, agent_dec_state, merge_type, inter_weight, role_mask)
  File "/home/ubuntu/anaconda3/envs/rods/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/ssd/lcq/RODS/models/BERT_interact/models/decoder.py", line 477, in forward
    step=step)
  File "/home/ubuntu/anaconda3/envs/rods/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/ssd/lcq/RODS/models/BERT_interact/models/decoder.py", line 186, in forward
    type="context")
  File "/home/ubuntu/anaconda3/envs/rods/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/ssd/lcq/RODS/models/BERT_interact/models/neural.py", line 341, in forward
    batch_size = key.size(0)
AttributeError: 'str' object has no attribute 'size'
*****************

I try to print the 'key'(batch_size = key.size(0)) in the neural.py, the last output is not tensor, but the string "last_hidden_state"

**Comment by xiaolinAndy** [comment]
Hi! Thanks for your pointing out the issue. I checked the code and find that it is due to the different version of transformers package. The version we use is 3.0.0 and we found that hte output formar of Bertmodel is different with higher version. You could wither use the lower verison or set the config.return_dict=False to ensure the correct output format. Sorry about not mentioning the requirement of this package in README.md. I have updated this information to it.

**Comment by lcqlalala** [comment]
Thanks
